"""Settings module for test app."""
from environs import Env

env = Env()
env.read_env()

ENV = "development"
TESTING = True
DEBUG = True
# This is generated by a pytest fixture and set there
SECRET_KEY = "not-so-secret-in-tests"
BCRYPT_LOG_ROUNDS = 4  # For faster tests; needs at least 4 to avoid "ValueError: Invalid rounds"
DEBUG_TB_ENABLED = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
PASSWORD_SCHEMES = "argon2"
PRESERVE_CONTEXT_ON_EXCEPTION = False
FLASK_CORS_ORIGINS = "*"

# JWT settings
JWT_ISSUER = env.str("JWT_ISSUER", default="quail")

PROJECT_NAME = "quail-test"
NOTIFICATION_EMAIL = "notifications@example.com"
ADMIN_EMAIL = "admins@example.com"
ADMIN_GROUP_NAME = "quail-admins"

# AWS config
DYNAMODB_PERMISSIONS_TABLE_NAME = "todo"
DYNAMODB_STATE_TABLE_NAME = "todo"
DYNAMODB_REGIONAL_METADATA_TABLE_NAME = "todo"

PROVISION_SFN_ARN = "todo"
CLEANUP_SFN_ARN = "todo"
UPDATE_SFN_ARN = "todo"
CFN_DATA_BUCKET = "todo"
STACK_SET_EXECUTION_ROLE_NAME = "todo"

SNS_ERROR_TOPIC_ARN = "todo"
CROSS_ACCOUNT_ROLE_NAME = "todo"
STACK_SET_ADMIN_ROLE_ARN = "todo"

CLEANUP_NOTICE_NOTIFICATION_HOURS = "todo"
TAG_CONFIG = "todo"
