from backend.settings.base import *

PROJECT_NAME = env.str("PROJECT_NAME")
NOTIFICATION_EMAIL = env.str("NOTIFICATION_EMAIL")
ADMIN_EMAIL = env.str("ADMIN_EMAIL")

DYNAMODB_REGIONAL_METADATA_TABLE_NAME = env.str("DYNAMODB_REGIONAL_METADATA_TABLE_NAME")
CLEANUP_SFN_ARN = env.str("CLEANUP_SFN_ARN")
CFN_DATA_BUCKET = env.str("CFN_DATA_BUCKET")
SNS_ERROR_TOPIC_ARN = env.str("SNS_ERROR_TOPIC_ARN")

TAG_CONFIG = env.str("TAG_CONFIG")
CLEANUP_NOTICE_NOTIFICATION_HOURS = env.str("CLEANUP_NOTICE_NOTIFICATION_HOURS")
