"""Settings module for test app."""
from environs import Env

env = Env()
env.read_env()

ENV = "development"
TESTING = True
DEBUG = True
# This is generated by a pytest fixture and set there
SQLALCHEMY_DATABASE_URI = env.str("TEST_DATABASE_URL")
SECRET_KEY = "not-so-secret-in-tests"
BCRYPT_LOG_ROUNDS = 4  # For faster tests; needs at least 4 to avoid "ValueError: Invalid rounds"
DEBUG_TB_ENABLED = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
PASSWORD_SCHEMES = "argon2"
PRESERVE_CONTEXT_ON_EXCEPTION = False

# JWT settings
JWT_ISSUER = env.str("JWT_ISSUER", default="quail")
