from backend.settings.base import *  # noqa: F403

PROJECT_NAME = env.str("PROJECT_NAME")  # noqa: F405
NOTIFICATION_EMAIL = env.str("NOTIFICATION_EMAIL")  # noqa: F405
ADMIN_EMAIL = env.str("ADMIN_EMAIL")  # noqa: F405

DYNAMODB_REGIONAL_METADATA_TABLE_NAME = env.str("DYNAMODB_REGIONAL_METADATA_TABLE_NAME")  # noqa: F405
CLEANUP_SFN_ARN = env.str("CLEANUP_SFN_ARN")  # noqa: F405
CFN_DATA_BUCKET = env.str("CFN_DATA_BUCKET")  # noqa: F405
SNS_ERROR_TOPIC_ARN = env.str("SNS_ERROR_TOPIC_ARN")  # noqa: F405

TAG_CONFIG = env.str("TAG_CONFIG")  # noqa: F405
CLEANUP_NOTICE_NOTIFICATION_HOURS = env.str("CLEANUP_NOTICE_NOTIFICATION_HOURS")  # noqa: F405
