name: CI

on:
  pull_request:
    branches: [ "master" ]

  push:
    branches: [ "master" ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint public api with flake8
        run: flake8
        working-directory: modules/backend/public-api

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check public api for black errors
        run: black --check .
        working-directory: modules/backend/public-api

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
        working-directory: modules/backend/public-api

      - name: Run pytest
        run: pytest
        working-directory: modules/backend/public-api

  cfn-nag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Lint Cloudformation
        uses: stelligent/cfn_nag@master
        with:
          input_path: demo/cfn-templates

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --production=false
        working-directory: modules/frontend/frontend

      - name: Run eslint
        run: npx eslint src/
        working-directory: modules/frontend/frontend

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init
        working-directory: demo

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: demo
